name = "ira"
version = "2.1.0"

[build]
link = "lapack"

[library]
type = "shared"
source-dir = "src"

[fortran]
implicit-external = true
source-form="default"

[dependencies]

[preprocess]
[preprocess.cpp]

[install]
library=true

