name = "ira"
version = "version.txt"

[build]
link = "lapack"

[library]
type = ["static", "shared"]
source-dir = "src"

[fortran]
implicit-external = true
source-form="default"

[dependencies]

[preprocess]
[preprocess.cpp]
macros = ["STRVERSION=\\\"2.2.0\\\"", "DATEVERSION=20250911" ]

[features]
optimized.flags = "-ffree-line-length-0 -fPIC -Ofast -ffast-math -march=native -funroll-loops"

[profiles]
release=["optimized"]

[install]
library=true

