[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "ira_mod"
dynamic = ["version"]
description = "Algorithms for Iterative Rotations and Assignments (IRA); Symmetry Operations FInder (SOFI); and Constrained Shortest Distance Assignment (CShDA)."
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "MAMMASMIAS Consortium"}]
license = "GPL-3.0-or-later OR Apache-2.0"
dependencies = ["numpy>=2.0.0"]

[project.urls]
Homepage = "https://mammasmias.github.io/IterativeRotationsAssignments/"
Repository = "https://github.com/mammasmias/IterativeRotationsAssignments"

[tool.scikit-build]
cmake.version = ">=3.21"
cmake.args = [ "-DIRA_INSTALL_PYTHON=ON" ]
wheel.packages = []  # Python files are installed via cmake install()

[tool.scikit-build.metadata.version]
provider = "scikit_build_core.metadata.regex"
input = "version.txt"
regex = "^(?P<value>\\d+\\.\\d+\\.\\d+)"

