#
# Fortran compiler
#
FCOMP = gfortran

#
# archiver
#
AR = ar

#
# lapack flag. 
# You can use: -L/path/to/lapack/ instead
#
LIBLAPACK = -llapack

#
# compilation flags
#
FFLAGS = -Wall -fdefault-real-8 -fbounds-check

SRC = $(PWD)
OBJ = $(SRC)/Obj

MOD = -I$(OBJ) -J$(OBJ)



# Executable names
#
IRAEQ_X = ira_eq.x
IRANEQ_X = ira_noneq.x
IRAGEN_X = ira_general.x
IRALIB = libira.a


#=======================
# object files
#
# utils
futils := \
	$(SRC)/sorting_module.f90 \
	$(SRC)/cshda.f90 \
	$(SRC)/ira_routines.f90
outils:= $(patsubst $(SRC)%,$(OBJ)%,$(futils:%.f90=%.o))

fread := $(SRC)/read_typ.f90
oread := $(patsubst $(SRC)%, $(OBJ)%, $(fread:%.f90=%.o))

f_eq := $(SRC)/ira_eq.f90
o_eq := $(patsubst $(SRC)%, $(OBJ)%, $(f_eq:%.f90=%.o))

f_neq := $(SRC)/ira_noneq.f90
o_neq := $(patsubst $(SRC)%, $(OBJ)%, $(f_neq:%.f90=%.o))

f_gen := $(SRC)/ira_general.f90
o_gen := $(patsubst $(SRC)%, $(OBJ)%, $(f_gen:%.f90=%.o))
#======================


default: msg

all: eq noneq general lib

$(OBJ)%.o: $(SRC)/%.f90
	$(FCOMP) $(FFLAGS) $(MOD) -c $< -o $@


eq: $(OBJ) $(IRAEQ_X)
noneq: $(OBJ) $(IRANEQ_X)
general: $(OBJ) $(IRAGEN_X)
lib: $(OBJ) $(IRALIB)

#
# object folder
#
$(OBJ):
	@if [ ! -d $(OBJ) ]; then mkdir $(OBJ) ; fi


#====
# Compile the executables
#====
$(IRAEQ_X): $(outils) $(oread) $(o_eq)
	$(FCOMP) $(FFLAGS) $(MOD) $^ -o $@ $(LIBLAPACK)


$(IRANEQ_X): $(outils) $(oread) $(o_neq)
	$(FCOMP) $(FFLAGS) $(MOD) $^ -o $@ $(LIBLAPACK)

$(IRAGEN_X): $(outils) $(oread) $(o_gen)
	$(FCOMP) $(FFLAGS) $(MOD) $^ -o $@ $(LIBLAPACK)


#====
# pack the library
#====
$(IRALIB): $(outils)
	$(AR) -rcv $@ $^

msg:
	@echo 'Use one of the following:'
	@echo ''
	@echo ' make all     -> compiles all programs included, and packs the library'
	@echo ' make eq      -> compiles the $(IRAEQ_X) program'
	@echo ' make noneq   -> compiles the $(IRANEQ_X) program'
	@echo ' make general -> compiles the $(IRAGEN_X) program'
	@echo ' make lib     -> compiles the $(IRALIB) library'
	@echo ''
	@echo ' make clean   -> remove all files generated by make'
	@echo ''
	@echo 'Quitting.'




clean:
	rm -f $(IRAEQ_X) $(IRANEQ_X) $(IRAGEN_X) $(IRALIB)
	rm -rf $(OBJ)


