#
# Fortran compiler
#
FCOMP = gfortran

#
# archiver
#
AR = ar

#
# lapack flag. 
# You can use: -L/path/to/lapack/ instead
#
LIBLAPACK = -llapack

#
# compilation flags
#
FFLAGS = -Wall -fdefault-real-8 -fbounds-check

SRC = $(PWD)
OBJ = $(SRC)/Obj

MOD = -I$(OBJ) -J$(OBJ)



# Produced filenames
#
IRAUNI_X = f90_program.x
IRALIB = libira.a
PY_MOD = ira_mod


#=======================
# object files
#
# utils
futils := \
	$(SRC)/sorting_module.f90 \
	$(SRC)/set_candidate.f90 \
	$(SRC)/cshda.f90 \
	$(SRC)/ira_routines.f90
outils:= $(patsubst $(SRC)%,$(OBJ)%,$(futils:%.f90=%.o))

fread := $(SRC)/read_typ.f90
oread := $(patsubst $(SRC)%, $(OBJ)%, $(fread:%.f90=%.o))

f_uni := $(SRC)/f90_program.f90
o_uni := $(patsubst $(SRC)%, $(OBJ)%, $(f_uni:%.f90=%.o))
#======================


default: msg

all : main lib pyf

$(OBJ)%.o: $(SRC)/%.f90
	$(FCOMP) $(FFLAGS) $(MOD) -c $< -o $@


main: $(OBJ) $(IRAUNI_X)
lib: $(OBJ) $(IRALIB)
pyf: $(PY_MOD)

#
# object folder
#
$(OBJ):
	@if [ ! -d $(OBJ) ]; then mkdir $(OBJ) ; fi


#====
# Compile the executable
#====
$(IRAUNI_X): $(outils) $(oread) $(o_uni)
	$(FCOMP) $(FFLAGS) $(MOD) $^ -o $@ $(LIBLAPACK)


#====
# pack the library
#====
$(IRALIB): $(outils)
	$(AR) -rcv $@ $^

#====
# generate the python module
#====
$(PY_MOD): $(futils)
	f2py3 $(LIBLAPACK) -c --fcompiler=$(FCOMP) --f90flags='$(FFLAGS)' ira_interf.pyf $^ -m $(PY_MOD)


msg:
	@echo 'Use one of the following:'
	@echo ''
	@echo ' make f90     -> compiles the f90 example program $(IRAUNI_X) executable'
	@echo ' make pyf     -> compiles the $(PY_MOD).* python module'
	@echo ' make lib     -> compiles the $(IRALIB) library'
	@echo ' make all     -> all of the above'
	@echo ''
	@echo ' make clean   -> remove all files generated by make'
	@echo ''
	@echo 'Quitting.'




clean:
	rm -rf $(IRAUNI_X) $(PY_MOD).* $(IRALIB)
	rm -rf $(OBJ)


